apiVersion: v1
kind: Service
metadata:
  name: easy-gate-service
  labels:
    app: easy-gate
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: easy-gate
